#!/usr/bin/env python

# Copyright 2011 GridCentric Inc.
# All Rights Reserved.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

# A simple script that uses the novaclient to communicate with Openstack to provide the gridcentric
# specific functionality.

import sys
import novaclient.client as novaclient



def usage():
    sys.stderr.write("usage: gc-nova <command>\n")
    sys.stderr.write("where command is one of the following:\n")
    sys.stderr.write("    suspend <instance id>\n")
    sys.stderr.write("        Creates a new clone base instance based off of the instance with the given id.")
    sys.stderr.write("\n")
    sys.stderr.write("    launch <instance id>\n")
    sys.stderr.write("        Launches a new clone instance based off of the base instance with the given id.")
    sys.stderr.write("\n")
    sys.stderr.flush()

if len(sys.argv) < 2:
    usage()
    exit()
 
command = sys.argv[1]

if command == 'suspend':
    instance_id = sys.argv[2]
    
    client = novaclient.HTTPClient('admin','admin','','http://localhost:8774/v1.1')
    client.post('/servers/%s/action' % instance_id,body={'gc_suspend':{}})
    
elif command == 'launch':
    instance_id = sys.argv[2]   
    
    client = novaclient.OpenStackClient('admin','admin','','http://localhost:8774/v1.1')
    client.post('/servers/%s/action' % instance_id,body={'gc_launch':{}})
