#!/bin/bash

set -e

# If the nova-compute process is running, then we start.
if initctl status nova-compute | grep process >/dev/null 2>&1; then
    service nova-gc restart 2>/dev/null || \
    service nova-gc start;
 else
    service nova-gc restart 2>/dev/null || true
fi
