#!/bin/sh
#
# cobalt-compute Gridcentric Openstack Nova Compute Extension
#

### BEGIN INIT INFO
# Provides:
# Required-Start: $remote_fs $network $syslog
# Required-Stop: $remote_fs $syslog
# Default-Stop: 0 1 6
# Short-Description: Cobalt Compute Daemon
# Description: Gridcentric extension to the Openstack Nova Compute service.
### END INIT INFO

. /etc/rc.d/init.d/functions
prog=cobalt-compute
user="root"
exec="/usr/bin/$prog"
configdir="/etc/nova"
logfile="/var/log/nova/cobalt.log"
pidfile="/var/run/nova/$prog.pid"

[ -e "/etc/sysconfig/$prog" ] && . "/etc/sysconfig/$prog"

lockfile="/var/lock/subsys/$prog"

start() {
    [ -x $exec ] || exit 5
    echo -n $"STARTING $prog: "
    daemon --user $user --pidfile $pidfile "$exec --config-dir=$configdir --logfile=$logfile &>/dev/null & echo \$! > $pidfile"
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    killproc -p $pidfile $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    status -p $pidfile $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}

case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac
exit $?
