#!/bin/bash

set -e

function restart_service {
    # If the nova-compute process is running, then we start.
    if initctl status nova-compute | grep process >/dev/null 2>&1; then
        service nova-gridcentric restart 2>/dev/null || \
        service nova-gridcentric start;
    else
        service nova-gridcentric restart 2>/dev/null || true
    fi
}

function add_extension {
    NOVA_CONF=$1

    if [ -f $NOVA_CONF ]; then
        # Add the extension.
        if ! cat $NOVA_CONF | grep osapi_extensions_path >/dev/null 2>&1; then
            echo "--osapi_extensions_api=/var/lib/nova/extensions" >> $NOVA_CONF
        fi
    fi

    # Restart the api service (if running).
    service nova-api restart 2>/dev/null || true
}

case $1 in
    configure)
        restart_service
        add_extension /etc/nova/nova.conf
        ;;
esac
