#!/bin/bash

set -e

function stop_service {
    # Always stop the service fully.
    service nova-gridcentric stop 2>/dev/null || true
}

function remove_extension {
    NOVA_CONF=$1
    EXTENSION=$2

    if [ -f $NOVA_CONF ]; then

        # Automatically remove the extension from nova.conf if it was added.
        cat $NOVA_CONF | \
            grep -v $EXTENSION > $NOVA_CONF.new && \
            mv $NOVA_CONF.new $NOVA_CONF || \
            rm -f $NOVA_CONF.new

        # Restart the api service (if running).
        service nova-api restart 2>/dev/null || true
    fi
}

case $1 in
    remove)
        remove_extension \
            /etc/nova/nova.conf \
            gridcentric.nova.osapi.gridcentric_extension.Gridcentric_extension
        stop_service
        ;;
esac
