#!/usr/bin/env python

import XenAPIPlugin


def suspend_vms(session, args):
    f = file('/tmp/vms.out','w')
    f.write("written!")
    f.write("\n")
    f.write("args: %s" % args)
    f.close()

    return "" # Dummy result


if __name__ == '__main__':
    XenAPIPlugin.dispatch({'suspend_vms': suspend_vms})


